# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b9bafb25691eb6f4cf16510012e7ea0aa5fdec2d4ac4f2cd0f8403f3928d6d090d0093958610d26932c4e9435e0ff9afa0587af72f04370771980440d917666

test:
  secret_key_base: f00eeeed0264964ea886d1dbbb30c428cba57b82576c1c83f41ae69d67e71fa998db997c18251d9eb2bf6acb6fbf803df5ac75e570352b53b899221afe8d1920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
